<?php
namespace app\modules\admin\controllers;

use app\modules\admin\models\Navigation;
use app\modules\admin\models\Page;
use app\modules\admin\models\Post;
use app\modules\admin\models\Site;
use Yii;
use yii\bootstrap\ActiveForm;
use yii\data\ActiveDataProvider;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\web\Controller;
use yii\web\ForbiddenHttpException;
use yii\web\NotFoundHttpException;
use yii\web\Response;


class BlogController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    public function init()
    {
        parent::init();
        Yii::$app->errorHandler->errorAction = 'admin/main/error';
    }

    public function beforeAction($action)
    {
        if (!Site::get('blog_module_enabled')) throw new ForbiddenHttpException('Module disabled. Enable first');
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actions()
    {
        $this->layout = 'main';
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function actionIndex(){
        $query = Post::find()->orderBy(['date' => SORT_ASC]);
        $dataProvider = new ActiveDataProvider([
            'query' => $query,
            'pagination' => [
                'pageSize' => 20,
                'forcePageParam' => false,
                'pageSizeParam' => false,
            ],
        ]);
        $models = $dataProvider->getModels();
        $count = $dataProvider->getTotalCount();
        $pagination = $dataProvider->pagination;
        return $this->render('index',[
            'models' => $models,
            'count' => $count,
            'pagination' => $pagination
        ]);
    }

    public function actionSearch($title){
        $query = Post::find()->where(['like', 'title', $title])->orderBy(['title' => SORT_ASC]);
        $dataProvider = new ActiveDataProvider([
            'query' => $query,
            'pagination' => [
                'pageSize' => 20,
                'forcePageParam' => false,
                'pageSizeParam' => false,
            ],
        ]);
        $models = $dataProvider->getModels();
        $count = $dataProvider->getTotalCount();
        $pagination = $dataProvider->pagination;
        return $this->render('index',[
            'models' => $models,
            'count' => $count,
            'pagination' => $pagination
        ]);
    }

    public function actionCreate(){
        $model = new Post();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->getSession()->setFlash('update', 'Post successfully created!');
            return $this->redirect('index');
        } else {
            return $this->render('create', [
                'model' => $model
            ]);
        }
    }

    public function actionUpdate($id)
    {
        $model = Post::findOne($id);
        if (!$model) throw new NotFoundHttpException('Record not found');

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->getSession()->setFlash('update', 'Post successfully updated!');
            return $this->redirect('index');
        } else {
            return $this->render('update', [
                'model' => $model
            ]);
        }
    }

    public function actionDelete($id)
    {
        Post::findOne($id)->delete();
        Yii::$app->getSession()->setFlash('update', 'Post successfully deleted!');
        return $this->redirect(\Yii::$app->request->getReferrer());
    }

}