<?php
namespace app\modules\admin\controllers;

use app\modules\admin\models\Category;
use app\modules\admin\models\Faq;
use app\modules\admin\models\Language;
use app\modules\admin\models\Site;
use app\modules\admin\models\Webinar;
use Yii;
use yii\bootstrap\ActiveForm;
use yii\data\ActiveDataProvider;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\web\Controller;
use yii\web\ForbiddenHttpException;
use yii\web\NotFoundHttpException;
use yii\web\Response;

/**
 * Created by PhpStorm.
 * User: ilya
 * Date: 21.12.16
 * Time: 14:50
 */
class FaqController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    public function init()
    {
        parent::init();
        Yii::$app->errorHandler->errorAction = 'admin/main/error';
    }

    public function beforeAction($action)
    {
        if (!Site::get('faq_module_enabled')) throw new ForbiddenHttpException('Module disabled. Enable first');
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actions()
    {
        $this->layout = 'main';
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
                'layout' => '@app/modules/admin/views/layouts/main'
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function actionIndex(){
        $query = Faq::find();
        $dataProvider = new ActiveDataProvider([
            'query' => $query,
            'pagination' => [
                'pageSize' => 20,
                'forcePageParam' => false,
                'pageSizeParam' => false,
            ],
        ]);
        $models = $dataProvider->getModels();
        $count = $dataProvider->getTotalCount();
        $pagination = $dataProvider->pagination;
        return $this->render('index',[
            'models' => $models,
            'count' => $count,
            'pagination' => $pagination
        ]);
    }

    public function actionSearch($title){
        $query = Faq::find()->where(['like', 'question', $title])->orWhere(['like', 'answer', $title]);
        $dataProvider = new ActiveDataProvider([
            'query' => $query,
            'pagination' => [
                'pageSize' => 20,
                'forcePageParam' => false,
                'pageSizeParam' => false,
            ],
        ]);
        $models = $dataProvider->getModels();
        $count = $dataProvider->getTotalCount();
        $pagination = $dataProvider->pagination;
        return $this->render('index',[
            'models' => $models,
            'count' => $count,
            'pagination' => $pagination
        ]);
    }

    public function actionCreate(){
        $model = new Faq();

        if (Yii::$app->request->isAjax && $model->load(Yii::$app->request->post())) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ActiveForm::validate($model);
        }

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->getSession()->setFlash('update', 'FAQ successfully created!');
            return $this->redirect(\Yii::$app->request->getReferrer());
        } else {
            return $this->renderAjax('create', [
                'model' => $model
            ]);
        }
    }

    public function actionUpdate($id)
    {
        $model = Faq::findOne($id);
        if (!$model) throw new NotFoundHttpException('Record not found');
        if (Yii::$app->request->isAjax && $model->load(Yii::$app->request->post())) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ActiveForm::validate($model);
        }

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->getSession()->setFlash('update', 'FAQ successfully updated!');
            return $this->redirect(\Yii::$app->request->getReferrer());
        } else {
            return $this->renderAjax('update', [
                'model' => $model
            ]);
        }
    }

    public function actionDelete($id)
    {
        Faq::findOne($id)->delete();
        Yii::$app->getSession()->setFlash('update', 'FAQ successfully deleted!');
        return $this->redirect(\Yii::$app->request->getReferrer());
    }

}