<?php
/**
 * Created by PhpStorm.
 * User: prog
 * Date: 07.07.18
 * Time: 18:31
 */

namespace app\modules\admin\models;


use app\models\Helper;
use yii\db\ActiveRecord;
use yii\web\UploadedFile;

class Faq extends ActiveRecord
{
    public static function tableName()
    {
        return 'faqs';
    }

    public function rules()
    {
        return [
            [['question', 'answer'], 'required'],
            [['question', 'answer', 'locale'], 'string'],
        ];
    }

    public function beforeSave($insert)
    {
        if ($this->isNewRecord){
            if (!$this->locale) $this->locale = 'en';
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}