<?php
/**
 * Created by PhpStorm.
 * User: prog
 * Date: 05.07.18
 * Time: 13:57
 */

namespace app\modules\admin\models;


use yii\db\ActiveRecord;

class Navigation extends ActiveRecord
{
    public static function tableName()
    {
        return 'navigation';
    }

    public function rules()
    {
        return [
            [['title'], 'required'],
            [['title', 'locale', 'anchor'], 'string'],
            ['position', 'integer'],
            ['position', 'default', 'value' => 0],
            ['in_footer', 'boolean'],
            ['pages', 'safe'],
        ];
    }

    public function beforeSave($insert)
    {

        if ($this->isNewRecord){
            if (!$this->locale) $this->locale = 'en';
        }

        if (is_array($this->pages)) {
            $pages = array_unique($this->pages);
            if (($key = array_search(0, $pages)) !== false) {
                unset($pages[$key]);
            }
            $this->pages = implode(', ', $pages);
        };
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

}