<?php
/**
 * Created by PhpStorm.
 * User: prog
 * Date: 01.09.18
 * Time: 14:11
 */

namespace app\modules\admin\models;


use app\models\Helper;
use Yii;
use yii\db\ActiveRecord;
use yii\web\UploadedFile;

class Post extends ActiveRecord
{
    public $_img;

    public static function tableName()
    {
        return 'posts';
    }

    public function rules()
    {
        return [
            [['title', 'preview', 'text'], 'required'],
            [['title', 'preview', 'text', 'slug', 'locale', 'meta_title', 'meta_description', 'keywords'], 'string'],
            [['hide', 'index', 'follow'], 'boolean'],
            [['views'], 'integer']
        ];
    }

    public function beforeSave($insert)
    {
        if ($this->isNewRecord){
            if (!$this->locale) $this->locale = 'en';
            $this->date = date('Y-m-d H:i:s');
            $this->created_by = \Yii::$app->user->id;
            $this->_img = UploadedFile::getInstance($this, '_img');
            if ($this->_img) {
                $name = Helper::RandomString(11);
                $filename = 'img/blog/' . $name . '.' . $this->_img->extension;
                $this->_img->saveAs($filename);
                $this->img = '/' . $filename;

            } else {
                $this->img = '/img/no-photo.png';
            }
        }

        $regex = [
            '/[^а-яА-Яa-zA-Z0-9#]/' => '-',
            '/[!@$%^&*;(),.?":{}|<>]/' => '-',
            '/ /' => '-'
        ];
        $this->slug = preg_replace(array_keys($regex), $regex, $this->slug);

        $this->_img = UploadedFile::getInstance($this, '_img');

        if ($this->_img) {
            if ($this->img != '/img/no-photo.png') {
                $this->_img->saveAs(ltrim($this->img, '/'));
            } else {
                $name = Helper::RandomString(11);
                $filename = 'img/blog/' . $name . '.' . $this->_img->extension;
                $this->_img->saveAs($filename);
                $this->img = '/' . $filename;
            }
        }

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

}