<?php
/**
 * Created by PhpStorm.
 * User: prog
 * Date: 31.08.18
 * Time: 15:02
 */

namespace app\modules\admin\models;


use Yii;
use yii\db\ActiveRecord;

class Site extends ActiveRecord
{

    public $robots;

    public static function tableName()
    {
        return 'site_settings';
    }

    public static function get($key){
        return self::findOne(1)->$key;
    }

    public function rules()
    {
        return [
            [['admin_email'], 'required'],
            [['user_module_enabled', 'faq_module_enabled', 'blog_module_enabled', 'language_module_enabled'], 'boolean'],
            [['robots'], 'string']
        ];
    }

    public function beforeSave($insert)
    {
        if ($this->user_module_enabled){
            $module = 'true';
        }else{
            $module = 'false';
        }

        //ENABLE/DISABLE USER MODULE

        $robots = fopen(Yii::$app->basePath.'/web/robots.txt', "w");
        fwrite($robots, $this->robots);
        fclose($robots);

        $path = Yii::$app->basePath.'/config/web.php';
        $tempPath = Yii::$app->basePath.'/config/_web.php';
        $finalPath = $path;
        copy($path, $tempPath);
        copy($path, $finalPath);

        $sh=fopen($tempPath, 'r');
        $th=fopen($finalPath, 'w');
        while (!feof($sh)) {
            $line=fgets($sh);
            if (strpos($line, '\'enableRegistration\' => ')!==false) {
                $line='\'enableRegistration\' => '.$module . PHP_EOL;
            }
            fwrite($th, $line);
        }

        fclose($sh);
        fclose($th);

        unlink($tempPath);
        shell_exec('sudo chown -R ubuntu:www-data '.Yii::$app->basePath.'/config/web.php');

        //UPDATE ADMIN EMAIL
        $path = Yii::$app->basePath.'/config/params.php';
        $tempPath = Yii::$app->basePath.'/config/_params.php';
        $finalPath = $path;
        copy($path, $tempPath);
        copy($path, $finalPath);

        $sh=fopen($tempPath, 'r');
        $th=fopen($finalPath, 'w');
        while (!feof($sh)) {
            $line=fgets($sh);
            if (strpos($line, '\'adminEmail\' => ')!==false) {
                $line='\'adminEmail\' => \''.$this->admin_email.'\''. PHP_EOL;
            }
            fwrite($th, $line);
        }

        fclose($sh);
        fclose($th);

        unlink($tempPath);
        shell_exec('sudo chown -R ubuntu:www-data '.Yii::$app->basePath.'/config/params.php');

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

}