<?php
/**
 * Created by PhpStorm.
 * User: prog
 * Date: 25.08.18
 * Time: 17:20
 */

namespace app\modules\admin\models;


use yii\db\ActiveRecord;
use yii\helpers\Html;
use yii\web\UploadedFile;

class Style extends ActiveRecord
{
    public $_logo;
    public $_background;
    public $_favicon;

    public static function tableName()
    {
        return 'style';
    }

    public function rules()
    {
        return [
            [['footer_color'], 'required'],
            [[
                'footer_color',
                'background_color',
                'active_link_color',
                'navbar_color',
                'navbar_links_color',
                'navbar_border_color',
                'navbar_align',
                'active_link_background',
                'link_hover_color',
                'link_hover_background',
                'ddm_background',
                'ddm_links',
                'ddm_border',
                'ddm_active',
                'ddm_hover_background',
                'ddm_hover_text',
                'ddm_active_background',
                'transition_color',
                'footer_background_color',
                'footer_titles_color',
                'footer_links_color',
                'footer_text_color',
                'footer_social_links_color',
                'footer_links_hover_color'
            ], 'string'],
            [['logo_width', 'transition_time'], 'integer'],
            [['background_img', 'fixed_navbar', 'navbar_transition', 'highlight_tab'], 'boolean']
        ];
    }

    public function attributeLabels()
    {
        return [
            'background_img' => 'Background image',
            'highlight_tab' => 'Highlight active tab',
            'ddm_background' => 'Dropdown menu background color',
            'ddm_links' => 'Dropdown menu links color',
            'ddm_border' => 'Dropdown menu border color',
            'ddm_active' => 'Dropdown menu active link color',
            'ddm_active_background' => 'Dropdown menu active link background color',
            'ddm_hover_background' => 'Dropdown menu hover link background color',
            'ddm_hover_text'  => 'Dropdown menu hover link text color',
            'navbar_transition' => 'Navbar transition (if fixed only)'
        ];
    }

    public function beforeSave($insert)
    {

        $this->_logo = UploadedFile::getInstance($this, '_logo');
        if ($this->_logo) {
            $name = 'logo';
            $path = 'img/' . $name . '.' . $this->_logo->extension;
            $this->_logo->saveAs($path);
            $this->logo = '/'.$path;
        }

        $this->_background = UploadedFile::getInstance($this, '_background');
        if ($this->_background) {
            $name = 'background';
            $path = 'img/' . $name . '.' . $this->_background->extension;
            $this->_background->saveAs($path);
            $this->background = '/'.$path;
        }

        $this->_favicon = UploadedFile::getInstance($this, '_favicon');
        if ($this->_favicon) {
            $name = 'favicon';
            $path = 'img/' . $name . '.' . $this->_favicon->extension;
            $this->_favicon->saveAs($path);
            $this->favicon = '/'.$path;
        }

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public static function get($key){
        switch ($key){
            case 'logo':
                return Html::img(self::findOne(1)->$key, ['id' => $key]);
                break;
            default:
                return self::findOne(1)->$key;
        }
    }
}